name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

env:
  SHFMT_VERSION: 3.1.2

jobs:
  formatting:
    name: Formatting

    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get -y install indent
          sudo wget https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64 -O /usr/local/bin/shfmt
          sudo chmod 755 /usr/local/bin/shfmt
      - name: Format code
        run: make format
      - name: Ensure no changes were made
        run: |
          if ! test -z "$(git status --porcelain=v1)"; then
            git diff
            exit 1
          fi

  linting:
    name: Linting

    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get -y install shellcheck cppcheck clang gcc clang-tools \
            indent uthash-dev libcap-dev libattr1-dev
          sudo wget https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64 -O /usr/local/bin/shfmt
          sudo chmod 755 /usr/local/bin/shfmt
      - name: Symlink /bedrock in place
        run: 'sudo ln -s "$(pwd)/src/slash-bedrock" /bedrock'
      - name: Lint code
        run: make check

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get -y install autoconf autopoint bison fakeroot gcc git gpg \
            gzip libtool make meson ninja-build pkg-config rsync
      - name: Build install script
        run: make SKIPSIGN=true

      - name: Rename install script
        run: mv bedrock-linux-*-*.sh bedrock-linux-installer.sh
      - name: Upload install script artifact
        uses: actions/upload-artifact@v2
        with:
          name: bedrock-installer
          path: bedrock-linux-installer.sh

  hijack-ubuntu:
    name: Hijack Ubuntu (without rebooting)

    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v2
      - name: Download install script
        uses: actions/download-artifact@v2
        with:
          name: bedrock-installer

      - name: Hijack
        run: 'echo "Not reversible!" | sudo color_priority= sh bedrock-linux-installer.sh --hijack'

  hijack-ubuntu-vm:
    name: Hijack Ubuntu VM

    needs: [build]

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install qemu-system-x86 cloud-image-utils
      - name: Download Ubuntu image
        run: wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img

      - name: Create cloud-init image file
        run: |
          # https://serverfault.com/a/940686
          # https://github.com/canonical/cloud-init/blob/master/doc/examples/cloud-config.txt
          ssh-keygen -t rsa -b 4096 -N "" -C "bedrock@github.com" -f ~/.ssh/id_rsa
          cat >user-data <<EOF
          #cloud-config
          ssh_authorized_keys:
            - $(cat ~/.ssh/id_rsa.pub)
          EOF
          cloud-localds user-data.img user-data

      - name: Start VM
        run: |
          qemu-system-x86_64 \
            -drive file=focal-server-cloudimg-amd64.img,format=qcow2 \
            -drive file=user-data.img,format=raw \
            -m 2G \
            -nic user,hostfwd=tcp:127.0.0.1:2222-:22 \
            -nographic &>vm-output.log </dev/null &

      - name: Wait for VM to boot
        run: |
          while pgrep qemu-system &>/dev/null && ! timeout 15 ssh -o StrictHostKeyChecking=accept-new -p 2222 ubuntu@localhost true; do
            sleep 10
          done
        timeout-minutes: 8

      - name: Download Bedrock install script
        uses: actions/download-artifact@v2
        with:
          name: bedrock-installer

      - name: Hijack VM
        run: |
          scp bedrock-linux-installer.sh ubuntu@localhost:~
          ssh -p 2222 ubuntu@localhost 'echo "Not reversible!" | sudo sh bedrock-linux-installer.sh --hijack; shutdown -r now'

      - name: Wait for VM to boot
        run: |
          while pgrep qemu-system &>/dev/null && ! timeout 15 ssh -o StrictHostKeyChecking=accept-new -p 2222 ubuntu@localhost true; do
            sleep 10
          done
        timeout-minutes: 8

      - name: Log into VM and run basic commands
        run: |
          ssh -p 2222 ubuntu@localhost '
          brl list
          ls -la /bedrock
          '

      - name: Upload VM output log
        uses: actions/upload-artifact@v2
        with:
          name: vm-output-log
          path: vm-output.log
        if: always()
